refactor: update to match changes in DT api (#384)
* refactor: update to match changes in DT api

* refactor: submitted_to_rpc() returns array directly

* refactor: DefaultApi->RpcApi for API client

* fix: match capitalization of apiKeyAuth scheme

* fix: generated schema includes /api/rpc prefix

* fix: get name_map from context correctly

This has been broken a loooong time...

* fix: .person not .id for draft author

* fix: references now in bare json response

* fix: json(), not to_json()

to_json() does not include read-only fields, json() serializes the whole model

* fix: naming in create_rpc_demo.py

* refactor: RpcApi -> PurpleApi

* style: ruff ruff

* chore(dev): fetch rpcapi.yaml from datatracker

* chore: fetch rpcapi from dt in app-init.sh

* chore: reconcile migration numbering

* ci: generate rpcapi schema via spectacular

diff --git a/update-rpcapi b/update-rpcapi
--- a/update-rpcapi
+++ b/update-rpcapi
@@ -1,8 +1,23 @@
 #!/bin/sh -e
-# Run this in the container after updating rpcapi.yaml!
+# Updates APIs
+#
+# Tries to get a current schema from the local datatracker instance, falling back
+# to its current file if that does not succeed.
+#
+WORKSPACE=/workspace
 
 # Generate OpenAPI schema for the Purple api
 ./manage.py spectacular --file purple_api.yaml
+
+# Try to fetch schema from datatracker
+RPCAPI_TMPDIR=$(mktemp -d)
+trap '/bin/rm -rf -- "$RPCAPI_TMPDIR"' EXIT
+if curl -s http://host.docker.internal:8000/api/schema/ -o "$RPCAPI_TMPDIR/rpcapi.yaml"; then
+  /bin/cp "$RPCAPI_TMPDIR/rpcapi.yaml" "$WORKSPACE/rpcapi.yaml"
+  echo "Updated rpcapi.yaml from local datatracker, using new schema."
+else
+  echo "Unable to update rpc.yaml from local datatracker, using existing schema."
+fi
 
 # Generate clients
 # Configure the generator in openapitools.json
